---
application:
  name: "tortoolkit-bot-2"
  project: "asdf2"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "Bot 2"
  version: "12"
routers:
- name: "main-tortoolkit-bot-2"
  routes:
  - application_name: "tortoolkit-bot-2"
    paths:
    - "/*"
