---
application:
  name: "tortoolkit-telegram"
  project: "asdf1"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "tortoolkit"
  version: "11"
routers:
- name: "main-tortoolkit-telegram"
  routes:
  - application_name: "tortoolkit-telegram"
    paths:
    - "/*"
